version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight web interface
    volumes:
      - redis_data:/data
    command: redis-stack-server --loadmodule /opt/redis-stack/lib/redisearch.so
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
